* Planificación Primer Año
* Qué quiero enseñar
Para poder definir los contenidos o lo que se pretende enseñar, utilizaremos el 
 - [ ] Explorar: Leer la web
   - [ ] Navegación
     - Acceder a la web usando las características comunes de un navegador.
     - Usar hiperlinks para acceder a un rango de recursos de la web.
     - Leer, evaluar y manipular URLs
     - Reconocimiento de pistas visuales en los servicios web
     - Explorar complementos y extensiones de los navegadores para proveerlos de funcionalidades adicionales.
   - [ ] Mecánica de la web
     - Usar y entender la diferencia entre URLs, direcciones IP y términos de búsqueda.
     - Identificar dónde está la información en la red de dispositivos que hace a Internet.
     - Exportar, mover y resguardar datos de servicios web.
     - Explicar el papel que juegan los algoritmos en la creación y manejo de contenido web.
     - Crear o modificar un algoritmo para traer contenido de la web.
   - [ ] Búsqueda
     - Desarrollar preguntas que ayuden a la búsqueda.
     - Usar y revisar palabras claves para que las búsquedas sean más eficientes.
     - Evaluar los resultados de las búsquedas para determinar si la información es relevante.
     - Encontrar información en tiempo real o información sensible a tiempo usando un rango de técnicas de búsqueda.
     - Descubrir información y recursos a través de preguntas dentro de las redes sociales.
   - [ ] Credibilidad
     - Comparar y contrastar información de varias fuentes.
     - Formular juicios basándose en las características técnicas y de diseño.
     - Discriminar entre contenido original y derivado.
     - Evaluar como las perspectivas y los propósitos dan forma a los recursos web.FIXME
   - [ ] Seguridad
     - Recomendar como evitar estafas online y 'phishing'.
     - Manejar y mantener la seguridad de las cuentas.
     - Encriptr datos y comunicaciones usando programas y complementos.
     - Cambiar el comportamiento por defecto de páginas, complementos y extensiones para hacer la navegación más segura.
 - [ ] Construir: Escribir en la web
   - [ ] Composición
     - [ ] Insertar hiperlinks en una página web.
     - Identificar y usar html tags.
     - Embeber contenido multimedia en una página web.
     - Crear recurso web acorde a medio/género.
     - Configurar y controlar un espacio de publicación web.
   - [ ] Remixado
     - 
    Identifying remixable content.
    Combining multimedia resources to create something new on the web.
    Shifting context and meaning by creating derivative content.
    Citing and referencing original content.
   - [ ] Diseño
    Using CSS properties to change the style and layout of a Web page.
    Demonstrating the difference between inline, embedded and external CSS.
    Improving user experiences through feedback and iteration.
    Creating device-agnostic web resources.
   - [ ] Codigo/Scripting
    Reading and explaining the structure of code.
    Identifying and applying common coding patterns and concepts.
    Adding comments to code for clarification and attribution.
    Applying a script framework.
    Querying a web service using an API.
   - [ ] Accesibilidad
    Using empathy and awareness to inform the design of web content that is accessible to all users.
    Designing for different cultures which may have different interpretations of design elements.
    Comparing and exploring how different interfaces impact diverse users.
    Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup.
    Comparing and contrasting how different interfaces impact diverse web users.
 - [ ] Conectar: Participar en la web
   - [ ] Compartir
    Creating and using a system to distribute web resources to others.
    Contributing and finding content for the benefit of others.
    Creating, curating, and circulating web resources to elicit peer feedback.
    Understanding the needs of audiences in order to make relevant contributions to a community.
    Identifying when it is safe to contribute content in a variety of situations on the web.
   - [ ] Colaboración
    Choosing a Web tool to use for a particular contribution/ collaboration.
    Co-creating Web resources.
    Configuring notifications to keep up-to-date with community spaces and interactions.
    Working towards a shared goal using synchronous and asynchronous tools.
    Developing and communicating a set of shared expectations and outcomes.
   - [ ] Participación
    Engaging in web communities at varying levels of activity.
    Respecting community norms when expressing opinions in web discussions.
    Making sense of different terminology used within online communities.
    Participating in both synchronous and asynchronous discussions.
   - [ ] Privacidad
    Debating privacy as a value and right in a networked world.
    Explaining ways in which unsolicited third parties can track users across the web.
    Controlling (meta)data shared with online services.
    Identifying rights retained and removed through user agreements.
    Managing and shaping online identities.
   - [ ] Prácticas Abiertas
    Distinguishing between open and closed licensing.
    Making web resources available under an open license.
    Contributing to an open source project.
    Advocating for an open web.
* Clase 1
** Instalación de firefox
1. Crear una carpeta llamada /opt/
2. Ir a [[http://mozilla.org][Mozilla.org]]
3. Hacer click en sistemas e idiomas
4. Buscar Lenguaje Español Argentina, la flechita con el Pinguino y el 64 abajo
5. Esperar
6. Esperar que baje
7. ir a /Lugares/ -> /Descargas/
8. Abrir Firefox
9. Exportar en la carpeta /opt/
10. /Sistema/ -> /Preferencias/ -> /Menu Principal/
11. Agregar el menú Firefox
